spring.application.name=progreso2-integracion-lopez-mario
server.port=8086

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5674
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

camel.springboot.main-run-controller=true
logging.level.edu.udla.integracion.progreso2=INFO
